version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    image: siwapp/siwapp
    volumes:
      - .:/app
    command: [rails, server, -b, '0.0.0.0']
    ports:
      - '3000:3000'
    depends_on:
      - db
