networks:
  front:
    external:
      name: front
services:
  db:
    image: postgres:9.6-alpine
    ports:
    - 5432:5432
    volumes:
    - data_volume:/var/lib/postgresql/data
  web:
    build: .
    command:
    - rails
    - server
    - -b
    - 0.0.0.0
    depends_on:
      - db
    image: siwapp/siwapp
    networks:
      default:
      front:
        aliases:
        - siwapp
    ports:
    - 3000:3000
    volumes:
      - .:/app
version: '2.0'
volumes:
  data_volume: {}
