services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    depends_on:
      - db
    image: siwapp/siwapp
    networks:
      default:
        aliases:
        - siwapp
    ports:
      - 3000:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
version: '3'
